apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
type: Opaque
data:
{{- if .Values.aws }}
  aws_access_key_id: {{ .Values.aws.access_key_id | b64enc }}
  aws_secret_access_key: {{ .Values.aws.secret_access_key | b64enc }}
{{- end }}
{{- if .Values.cloudflare }}
  cloudflare_email: {{ .Values.aws.cloudflare.email | b64enc }}
  cloudflare_api_key: {{ .Values.aws.cloudflare.api_key | b64enc }}
{{- end }}
{{- if .Values.do }}
  do_auth_token: {{ .Values.do.auth_token | b64enc }}
{{- end }}
{{- if .Values.dnsimple }}
  dnsimple_oauth_token: {{ .Values.dnsimple.oauth_token | b64enc }}
{{- end }}
{{- if .Values.dnsmadeeasy }}
  dnsmadeeasy_api_key: {{ .Values.dnsmadeeasy.api_key | b64enc }}
  dnsmadeeasy_api_secret: {{ .Values.dnsmadeeasy.api_secret | b64enc }}
  dnsmadeeasy_sandbox: {{ .Values.dnsmadeeasy.sandbox | b64enc }}
{{- end }}
{{- if .Values.dyn }}
  dyn_customer_name: {{ .Values.dyn.customer_name | b64enc }}
  dyn_user_name: {{ .Values.dyn.user_name | b64enc }}
  dyn_password: {{ .Values.dyn.password | b64enc }}
{{- end }}
{{- if .Values.gandi }}
  gandi_api_key: {{ .Values.gandi.api_key | b64enc }}
{{- end }}
{{- if .Values.google }}
  gce_project: {{ .Values.google.gce_project | b64enc }}
  google_application_credentials: {{ .Values.google.application_credentials | b64enc }}
{{- end }}
{{- if .Values.namecheap }}
  namecheap_api_user: {{ .Values.namecheap.api_user | b64enc }}
  namecheap_api_key: {{ .Values.namecheap.api_key | b64enc }}
{{- end }}
{{- if .Values.ovh }}
  ovh_endpoint: {{ .Values.ovh.endpoint | b64enc }}
  ovh_application_key: {{ .Values.ovh.application_key | b64enc }}
  ovh_application_secret: {{ .Values.ovh.application_secret | b64enc }}
  ovh_consumer_key: {{ .Values.ovh.consumer_key | b64enc }}
{{- end }}
{{- if .Values.pdns }}
  pdns_api_key: {{ .Values.pdns.api_key | b64enc }}
{{- end }}
{{- if .Values.rfc2136 }}
  rfc2136_nameserver: {{ .Values.rfc2136.nameserver | b64enc }}
  rfc2136_tsig_algorigthm: {{ .Values.rfc2136.tsig_algorigthm | b64enc }}
  rfc2136_tsig_key: {{ .Values.rfc2136.tsig_key | b64enc }}
  rfc2136_tsig_secret: {{ .Values.rfc2136.tsig_secret | b64enc }}
{{- end }}
{{- if .Values.vultr }}
  vultr_api_key: {{ .Values.vultr.api_key | b64enc }}
{{- end }}
